# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import helloworld_pb2 as helloworld__pb2


class BookStub(object):
  """interface de serviço
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Add = channel.unary_unary(
        '/Book/Add',
        request_serializer=helloworld__pb2.AddRequest.SerializeToString,
        response_deserializer=helloworld__pb2.AddReply.FromString,
        )
    self.Remove = channel.unary_unary(
        '/Book/Remove',
        request_serializer=helloworld__pb2.RemoveRequest.SerializeToString,
        response_deserializer=helloworld__pb2.RemoveReply.FromString,
        )
    self.Consult = channel.unary_unary(
        '/Book/Consult',
        request_serializer=helloworld__pb2.ConsultRequest.SerializeToString,
        response_deserializer=helloworld__pb2.ConsultReply.FromString,
        )


class BookServicer(object):
  """interface de serviço
  """

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Remove(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Consult(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BookServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=helloworld__pb2.AddRequest.FromString,
          response_serializer=helloworld__pb2.AddReply.SerializeToString,
      ),
      'Remove': grpc.unary_unary_rpc_method_handler(
          servicer.Remove,
          request_deserializer=helloworld__pb2.RemoveRequest.FromString,
          response_serializer=helloworld__pb2.RemoveReply.SerializeToString,
      ),
      'Consult': grpc.unary_unary_rpc_method_handler(
          servicer.Consult,
          request_deserializer=helloworld__pb2.ConsultRequest.FromString,
          response_serializer=helloworld__pb2.ConsultReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Book', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
