# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import livro_pb2 as livro__pb2


class GreeterStub(object):
  """interface de serviço
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AdicionarLivro = channel.unary_unary(
        '/Greeter/AdicionarLivro',
        request_serializer=livro__pb2.Livro.SerializeToString,
        response_deserializer=livro__pb2.Resposta.FromString,
        )
    self.RemoverLivro = channel.unary_unary(
        '/Greeter/RemoverLivro',
        request_serializer=livro__pb2.Titulo.SerializeToString,
        response_deserializer=livro__pb2.Resposta.FromString,
        )
    self.ListarLivros = channel.unary_unary(
        '/Greeter/ListarLivros',
        request_serializer=livro__pb2.Request.SerializeToString,
        response_deserializer=livro__pb2.Resposta.FromString,
        )


class GreeterServicer(object):
  """interface de serviço
  """

  def AdicionarLivro(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoverLivro(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListarLivros(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AdicionarLivro': grpc.unary_unary_rpc_method_handler(
          servicer.AdicionarLivro,
          request_deserializer=livro__pb2.Livro.FromString,
          response_serializer=livro__pb2.Resposta.SerializeToString,
      ),
      'RemoverLivro': grpc.unary_unary_rpc_method_handler(
          servicer.RemoverLivro,
          request_deserializer=livro__pb2.Titulo.FromString,
          response_serializer=livro__pb2.Resposta.SerializeToString,
      ),
      'ListarLivros': grpc.unary_unary_rpc_method_handler(
          servicer.ListarLivros,
          request_deserializer=livro__pb2.Request.FromString,
          response_serializer=livro__pb2.Resposta.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
